# Generated by Django 4.2.3 on 2023-08-21 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('fio', models.CharField(max_length=100)),
                ('balls', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mode', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orderedcall',
            options={'verbose_name': 'Заказной звокнок', 'verbose_name_plural': 'Заказые звонки'},
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='phone',
            field=models.CharField(max_length=17),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('content', models.TextField()),
                ('images', models.ImageField(upload_to='reviews/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeUses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessid', models.CharField(max_length=100)),
                ('baseCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ballsType', models.CharField(max_length=10)),
                ('balls', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fio', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('messenger', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('promocode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
